version: "3.7"

services:
  app:
    image: ghcr.io/jdworkoutapp/jd_workout_golang:latest
    tty: true
    stdin_open: true
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./.env:/app/.env
      - ./credentials.json:/app/credential/google/credentials.json
    environment:
      - GO111MODULE=on
  mysql:
    image: ghcr.io/jdworkoutapp/jd_workout_golang_mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jd_workout
      MYSQL_USER: test
      MYSQL_PASSWORD: test
volumes:
  mysql_data:
