version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerfileDev
    tty: true
    stdin_open: true
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/app
  mysql:
      build:
        context: .
        dockerfile: ./docker/mysql/DockerfileDev
      ports:
        - "${DB_PORT:-3306}:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: jd_workout
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        TZ: Asia/Taipei
      volumes:
          - 'mysql_data:/var/lib/mysql'
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/DockerfileDev
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
    volumes:
      - redis_data:/data
  lint:
    build:
      context: .
      dockerfile: ./docker/lint/DockerfileDev
    volumes:
      - .:/app
    working_dir: /app
    command: [ "tail", "-f", "/dev/null" ]
volumes:
  mysql_data:
  redis_data:
