definitions:
  auth.registerForm:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Logs in a user with the provided email and password, and generates
        a JWT token for the user
      parameters:
      - description: User email
        in: formData
        name: email
        required: true
        type: string
      - description: User password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{''message'': ''login success'', ''token'': ''JWT token''}'
          schema:
            type: string
        "422":
          description: '{''message'': ''帳號或密碼錯誤'', ''error'': ''error message''}'
          schema:
            type: string
      summary: Login user
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: user register
      parameters:
      - description: registerForm
        in: body
        name: registerForm
        required: true
        schema:
          $ref: '#/definitions/auth.registerForm'
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "register success"}'
          schema:
            type: string
        "422":
          description: '{"message": "Email 重複", "error": "duplicate email"}'
          schema:
            type: string
        "500":
          description: '{"message": "register failed", "error": "server error"}'
          schema:
            type: string
      summary: register
      tags:
      - Auth
swagger: "2.0"
