name: CI

on:
  pull_request:
    branches:
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint check
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test
        run: |
          export PROCESS_TYPE=ci && make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.out
           fail_ci_if_error: true
           verbose: true