name: CI

on:
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test
        run: |
          export PROCESS_TYPE=ci && make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.txt